spring.application.name=MediSmart

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

jwt.secret-key=${JWT_SECRET_KEY}

spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

agora.app-id=${AGORA_APP_ID}
agora.app-certificate=${AGORA_APP_CERTIFICATE}